apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qe28iw57x-go
  janus-idp.io/tekton: qe28iw57x-go
  backstage.io/kubernetes-id: qe28iw57x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qe28iw57x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
